version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis:latest

  # this is the main proxy, request router
  # very important - the main gate to the app
  nginx:
    restart: always  # restarting in case of crashing
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:  # not 100% necessary in this case but can be helpful sometimes
      - api
      - client

  api:    # we used to call this service 'server' but it conflicts with nginx file, so we changed to api
    build:
      dockerfile: Dockerfile.dev  # no path here
      context: ./server  # here is a working (surce) directory
    volumes:
      - /app/node_modules  # do not map it! leave it alone as it is
      - ./server:/app  # map /app to ./server local directory
    environment:
      # an envirinment variable without "=..." will cause that
      # docker-compose will try to take this env var from the local computer
      # where we start the environment from
      - REDIS_HOST=redis  # name of the docker-compose service
      - REDIS_PORT=6379
      - PGUSER=postgres # default user for postgres
      - PGHOST=postgres # here we refer to the service in docker-compose
      - PGDATABASE=postgres # default db
      - PGPASSWORD=postgres_password # password set in postgres service above
      - PGPORT=5432 # default postgres port

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0  # issue fix - see video 133

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


